setono_sylius_recommendations_admin_recommendations_index:
    path: /recommendations
    methods: [GET,POST]
    defaults:
        _controller: setono_sylius_recommendations.controller.admin.action.recommendations

setono_sylius_recommendations_admin_ajax_product_variant_by_code:
    path: /ajax/recommendations/product-variant/by-code
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_variant::indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findBy
                arguments: [code: $code]
